import { test, before } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { buildIndex, accessStops, searchWindow } from './router.js';

/**
 * Tests against the REAL ingested network rather than a fixture.
 *
 * These catch a different class of bug from router.test.js: not "does the
 * algorithm work" but "does it produce sane journeys over 113,835 real German
 * services". Every failure here has been a real product defect — a phantom
 * S-Bahn leg before the real train, a six-hour wait sold as a connection, a
 * missing night train.
 *
 * Skipped when src/data/network.json is absent, since it is generated by
 * `npm run data:ingest` and deliberately not committed (35MB).
 */

const NETWORK = 'src/data/network.json';
const available = existsSync(NETWORK);

let index = null;
const PLACES = {
  berlin: [52.5118, 13.3782],
  munich: [48.1402, 11.5600],
  hamburg: [53.5528, 10.0067],
  cologne: [50.9430, 6.9589],
  frankfurt: [50.1070, 8.6638],
  vienna: [48.1856, 16.3367],
  stuttgart: [48.7838, 9.1817],
  leipzig: [51.3456, 12.3823],
};

before(() => {
  if (!available) return;
  index = buildIndex(JSON.parse(readFileSync(NETWORK, 'utf8')));
});

function plan(from, to, hour = 8) {
  const o = accessStops(index, ...PLACES[from], 4000, 8);
  const d = accessStops(index, ...PLACES[to], 4000, 8);
  return searchWindow(index, o, d, hour * 60, {
    windowMin: 12 * 60, stepMin: 180, maxRounds: 3, maxJourneys: 8,
  });
}

const it = available ? test : test.skip;

it('the ingested network has the shape the app expects', () => {
  assert.ok(index.network.stops.length > 5000, 'expected thousands of stops');
  assert.ok(index.network.services.length > 50000, 'expected tens of thousands of services');
  assert.ok(index.network.sources?.length, 'sources must be recorded for attribution');
  for (const s of index.network.sources) {
    assert.ok(s.attribution, `${s.id} must carry an attribution string`);
    assert.ok(s.licence, `${s.id} must record its licence`);
  }
});

it('every stop has usable coordinates', () => {
  for (const s of index.network.stops) {
    assert.ok(Number.isFinite(s.y) && Math.abs(s.y) <= 90, `bad latitude: ${s.n}`);
    assert.ok(Number.isFinite(s.x) && Math.abs(s.x) <= 180, `bad longitude: ${s.n}`);
  }
});

it('finds the direct ICE between Berlin and Munich', () => {
  const js = plan('berlin', 'munich');
  assert.ok(js.length, 'expected journeys');
  const direct = js.find((j) => j.transfers === 0);
  assert.ok(direct, 'Berlin-Munich has a direct ICE; the search must find it');
  assert.match(direct.legs.find((l) => l.mode !== 'walk').service, /^ICE/,
    'the direct service should be an ICE');
  // Real timetable: the fastest ICE does it in about four hours.
  assert.ok(direct.durationMin > 210 && direct.durationMin < 330,
    `expected roughly 4h, got ${direct.durationMin}min`);
});

it('does not prefix journeys with a pointless local hop', () => {
  // The S-Bahn platform is nearest a city-centre coordinate, so ranking access
  // stops by distance used to start every journey with an S-Bahn ride to reach
  // the long-distance platforms of the same station.
  for (const [from, to] of [['berlin', 'munich'], ['hamburg', 'cologne'], ['munich', 'hamburg']]) {
    for (const j of plan(from, to)) {
      const first = j.legs.find((l) => l.mode !== 'walk');
      if (!first) continue;
      const isLocalPrefix = /^(S\d|S-Bahn)/i.test(first.service ?? '');
      const veryShort = first.arriveMin - first.departMin < 10;
      assert.ok(!(isLocalPrefix && veryShort),
        `${from}->${to} starts with a throwaway ${first.service} leg`);
    }
  }
});

it('never sells a multi-hour wait as a connection', () => {
  for (const [from, to] of [['frankfurt', 'vienna'], ['berlin', 'cologne'], ['stuttgart', 'leipzig']]) {
    for (const j of plan(from, to, 9)) {
      const rides = j.legs.filter((l) => l.mode !== 'walk');
      for (let i = 1; i < rides.length; i++) {
        const wait = rides[i].departMin - rides[i - 1].arriveMin;
        const boardingSleeper = rides[i].mode === 'night_rail';
        assert.ok(wait <= (boardingSleeper ? 300 : 180),
          `${from}->${to}: ${wait}min wait at ${rides[i].from.name}`);
      }
    }
  }
});

it('legs are chronologically consistent within a journey', () => {
  for (const [from, to] of [['berlin', 'munich'], ['frankfurt', 'vienna']]) {
    for (const j of plan(from, to, 10)) {
      let prev = -Infinity;
      for (const l of j.legs) {
        assert.ok(l.departMin >= prev - 1, `leg departs before the previous arrives`);
        assert.ok(l.arriveMin >= l.departMin, `leg arrives before it departs`);
        prev = l.arriveMin;
      }
      assert.equal(j.departMin, j.legs[0].departMin);
      assert.equal(j.arriveMin, j.legs[j.legs.length - 1].arriveMin);
      assert.equal(j.durationMin, j.arriveMin - j.departMin);
    }
  }
});

it('journeys actually start and end near the requested places', () => {
  const js = plan('hamburg', 'cologne');
  assert.ok(js.length);
  for (const j of js) {
    const rides = j.legs.filter((l) => l.mode !== 'walk');
    assert.match(rides[0].from.name, /Hamburg/i, 'must start in Hamburg');
    assert.match(rides[rides.length - 1].to.name, /Köln|Koln|Cologne/i, 'must end in Cologne');
  }
});

it('finds an overnight option on a corridor that has one', () => {
  // Frankfurt to Vienna is served overnight; verified live against the feed.
  const js = plan('frankfurt', 'vienna', 16);
  assert.ok(js.length, 'expected journeys');
  const sleeper = js.find((j) => j.hasSleeper);
  assert.ok(sleeper, 'a late-afternoon Frankfurt-Vienna search should surface a sleeper');
  assert.ok(sleeper.sleeperMin > 120, 'the sleeping portion should be substantial');
});

it('price is null across every real journey', () => {
  for (const [from, to] of [['berlin', 'munich'], ['frankfurt', 'vienna'], ['hamburg', 'cologne']]) {
    for (const j of plan(from, to)) {
      assert.equal(j.price, null);
      for (const l of j.legs) assert.equal(l.price, null);
    }
  }
});

it('answers a realistic search fast enough to feel instant', () => {
  const t = Date.now();
  plan('berlin', 'munich');
  const ms = Date.now() - t;
  // Cold, uncached, on a laptop. The server caches, so this is the worst case.
  assert.ok(ms < 6000, `search took ${ms}ms, which a user would feel as broken`);
});

it('a search between two places with no rail link returns nothing, not nonsense', () => {
  // Two coordinates in the middle of the North Sea.
  const o = accessStops(index, 56.0, 3.0, 4000, 8);
  assert.equal(o.length, 0, 'there is no station in the North Sea');
});
